uvmf:
  environments:
    execute:
      agents:
      - initiator_responder: INITIATOR
        name: execute_in_agent
        type: execute_in
      - initiator_responder: RESPONDER
        name: execute_out_agent
        type: execute_out
      analysis_components:
      - name: execute_pred
        parameters: []
        type: execute_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: lc3_prediction_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: execute_sb
        sb_type: uvmf_in_order_scoreboard
        trans_type: execute_out_transaction
      subenvs: []
      tlm_connections:
      - driver: execute_in_agent.monitored_ap
        receiver: execute_pred.execute_in_agent_ae
        validate: 'True'
      - driver: execute_pred.execute_sb_ap
        receiver: execute_sb.expected_analysis_export
        validate: 'True'
      - driver: execute_out_agent.monitored_ap
        receiver: execute_sb.actual_analysis_export
        validate: 'True'
